% n is the number of rows and columns of coordinate frames to plot.
n = [ 2 6 ];
% Equally space the coordinate frames across the X-Y plane.
X = linspace( -n(2) / 2 + 0.5, n(2) / 2 - 0.5, n(2) );
Y = linspace( -n(1) / 2 + 0.5, n(1) / 2 - 0.5, n(1) );
[ X, Y, Z ] = meshgrid( X, Y, 0 );
t = [ X(:) Y(:) Z(:) ];
% Generate random rotations for each coordinate frame.
R = quat2rotm( randrot( 1, prod( n ) ) );
% Define the options for plotframe used to randomise the coordinate frames.
minMaxVectorLength = [ 0.3 0.7 ];
options = { 'LabelBasis', { true, false }, ...
            'Labels', { {'X','Y','Z'}, {'x','y','z'}, {'i','j','k'} }, ...
            'BasisColors', { {'r','g','b'}, 'k', ...
                             repelem( [0.4 0.6 0.8]', 1, 3 ), ...
                             {'r','g','b'} }, ...
            'LineStyle', { '-', '-.' }, ...
            'MaxHeadSize', { 0.4, 0.2, 0.6 }, ...
            'Alignment', { 'tail', 'center', 'tail' }, ...
            'Marker', { 'none', 'o' }, ...
            'LineWidth', { 2, 1, 3 }, ...
            'TextProperties', { {}, {'FontSize',13}, ...
                                {'FontWeight','bold'}, ...
                                {'FontAngle','italic'} } };
% Plot the coordinate frames.
f = figure;
ax = axes( f, 'DataAspectRatio', [1 1 1], 'View', [0 90], ...
    'XColor', 'none', 'YColor', 'none', 'ZColor', 'none' );
for i = 1 : prod( n )
    iOptions = options;
    % Select randomly select options for this coordinate frame. Use each
    % options for at least one coordinate frame.
    for j = 2 : 2 : numel( options )
        if i <= numel( iOptions{j} )
            iOptions{j} = iOptions{j}{i};
        else
            iOptions(j) = randsample( iOptions{j}, 1 );
        end
    end
    vectorLength = rand * range( minMaxVectorLength ) + ...
        minMaxVectorLength(1);
    % Marker options are only relevant when Marker='o'.
    plotframe( R(:,:,i), t(i,:), vectorLength, iOptions{:}, ...
        MarkerSize=6*vectorLength, MarkerEdgeColor='k', ...
        MarkerFaceColor='k', Parent=ax )
end
axis( ax, 'tight' )